services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-ingestion
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - poupeai-network

  minio:
    image: minio/minio
    container_name: minio-ingestion
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    networks:
      - poupeai-network

networks:
  poupeai-network:
    driver: bridge